version: "3.8"

services:
  cashclock:
    hostname: cashclock
    ports:
      - 80:80
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    restart: always
    environment:
      - GENERATE_SOURCEMAP=false
    networks:
      - proxy
    labels:
    - 'traefik.enable=true'
    - 'traefik.http.routers.librespeed.rule=Host(`cashclock.myngz.com`)'
    - 'traefik.http.routers.librespeed.entrypoints=websecure'
    - 'traefik.http.routers.librespeed.tls.certresolver=letsencrypt'

networks:
  proxy:
    external: false
    name: proxy
