version: "3.4"

services:
  cashclock:
    hostname: cashclock
    ports:
      - 420:420
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    restart: always
    environment:
      - GENERATE_SOURCEMAP=false
      - NGINX_PORT=420
    networks:
      - nginx-pm_default

networks:
  nginx-pm_default:
    external: false
    name: nginx-pm_default
