version: "3.8"

services:
  cashclock:
    container_name: cashclock
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - GENERATE_SOURCEMAP=false
    networks:
      - proxy
    labels:
    - 'autoheal=true'
    - 'traefik.enable=true'
    - 'traefik.http.routers.cashclock.rule=Host(`$DOMAIN`)'
    - 'traefik.http.routers.cashclock.entrypoints=websecure'
    - 'traefik.http.routers.cashclock.tls.certresolver=letsencrypt'

networks:
  proxy:
    external: false
    name: proxy
