version: "3.4"

services:
  cashclock:
    hostname: cashclock
    ports:
      - 420:420
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    restart: always
    environment:
      - GENERATE_SOURCEMAP=false
      - NGINX_PORT=420
    networks:
      - nginx-network

networks:
  nginx-network:
    external:
      name: nginx-network
