version: "3.8"

services:
  cashclock:
    container_name: cashclock
    ports:
      - 80
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    restart: always
    environment:
      - GENERATE_SOURCEMAP=false
    networks:
      - proxy
    labels:
    - 'traefik.enable=true'
    - 'traefik.http.routers.cashclock.rule=Host(`cashclock.myngz.com`)'
    - 'traefik.http.routers.cashclock.entrypoints=websecure'
    - 'traefik.http.routers.cashclock.tls.certresolver=letsencrypt'

networks:
  proxy:
    external: false
    name: proxy
