version: "3.4"

services:
  cashclock:
    hostname: cashclock
    ports:
      - 80:420
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    restart: always
    networks:
      - nginx-network

networks:
  nginx-network:
    external:
      name: nginx-network
