name: Docker Prod

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Docker run
        run: docker-compose up -d --force-recreate --build
